"use client";

import { useState } from "react";
import { anvilPriorWorkPenalty, beaconBlocks, brewingDetails, calculatePotion, damageAfterArmor, durabilityDetails, netherCoordinate, smeltingDetails, stackBreakdown } from "../lib/minecraft-tools";

function NumberField({ id, label, value, onChange, min = 0, step = 1 }: { id: string; label: string; value: string; onChange: (value: string) => void; min?: number; step?: number }) {
  return <div className="field"><label htmlFor={id}>{label}</label><input id={id} type="number" min={min} step={step} value={value} onChange={(event) => onChange(event.target.value)} required /></div>;
}

function Result({ label, value, note }: { label: string; value: string; note: string }) {
  return <div className="result" aria-live="polite"><span className="result-label">{label}</span><strong className="result-number">{value}</strong><p className="result-note">{note}</p></div>;
}

export function EnchantmentCalculator() {
  const [cost, setCost] = useState("5"); const [uses, setUses] = useState("0"); const [result, setResult] = useState<number | null>(null);
  return <div className="panel calculator-panel"><h2>Estimate anvil XP cost</h2><p className="panel-intro">Enter the XP level cost shown by your anvil and the number of previous anvil uses on the item.</p><form onSubmit={(event) => { event.preventDefault(); setResult(Number(cost) + anvilPriorWorkPenalty(Number(uses))); }}><div className="form-grid"><NumberField id="enchant-cost" label="Anvil cost (levels)" value={cost} onChange={setCost} min={1} /><NumberField id="prior-uses" label="Previous anvil uses" value={uses} onChange={setUses} /></div><button className="primary-button" type="submit">Calculate cost</button></form>{result !== null && <Result label="Estimated total" value={`${result} levels`} note={`Includes a ${anvilPriorWorkPenalty(Number(uses))}-level prior work penalty.`} />}</div>;
}

export function PotionCalculator() {
  const [base, setBase] = useState("180"); const [modifier, setModifier] = useState<"none" | "redstone" | "glowstone">("none"); const [result, setResult] = useState<{ seconds: number; amplifier: number } | null>(null);
  return <div className="panel calculator-panel"><h2>Plan potion duration</h2><p className="panel-intro">Start with the base effect duration, then choose the brewing modifier you plan to add.</p><form onSubmit={(event) => { event.preventDefault(); setResult(calculatePotion(Number(base), modifier)); }}><div className="form-grid"><NumberField id="potion-duration" label="Base duration (seconds)" value={base} onChange={setBase} min={1} /><div className="field"><label htmlFor="potion-modifier">Brewing modifier</label><select id="potion-modifier" value={modifier} onChange={(event) => setModifier(event.target.value as typeof modifier)}><option value="none">None</option><option value="redstone">Redstone · longer</option><option value="glowstone">Glowstone · stronger</option></select></div></div><button className="primary-button" type="submit">Calculate potion</button></form>{result !== null && <Result label="Potion result" value={`${result.seconds}s · Level ${result.amplifier}`} note={result.amplifier > 1 ? "Glowstone increases the effect level and reduces duration in-game." : "Redstone extends duration to eight-thirds of the base duration."} />}</div>;
}

export function DamageCalculator() {
  const [damage, setDamage] = useState("8"); const [armor, setArmor] = useState("0"); const [toughness, setToughness] = useState("0"); const [critical, setCritical] = useState(false); const [result, setResult] = useState<number | null>(null);
  return <div className="panel calculator-panel"><h2>Estimate damage after armor</h2><p className="panel-intro">Compare a hit against a target&apos;s armor. This uses the standard Java Edition armor reduction formula.</p><form onSubmit={(event) => { event.preventDefault(); setResult(damageAfterArmor(Number(damage), Number(armor), Number(toughness), critical)); }}><div className="form-grid"><NumberField id="raw-damage" label="Raw weapon damage" value={damage} onChange={setDamage} min={0} step={0.5} /><NumberField id="armor-value" label="Target armor points" value={armor} onChange={setArmor} min={0} /><NumberField id="armor-toughness" label="Armor toughness" value={toughness} onChange={setToughness} min={0} /><label className="check-field"><input type="checkbox" checked={critical} onChange={(event) => setCritical(event.target.checked)} /> Critical hit</label></div><button className="primary-button" type="submit">Calculate damage</button></form>{result !== null && <Result label="Damage dealt" value={result.toFixed(2)} note="Estimated damage depends on the target's current health and game version." />}</div>;
}

export function NetherPortalCalculator() {
  const [x, setX] = useState("0"); const [z, setZ] = useState("0"); const [direction, setDirection] = useState<"to-nether" | "to-overworld">("to-nether"); const [result, setResult] = useState<{ x: number; z: number } | null>(null);
  return <div className="panel calculator-panel"><h2>Convert portal coordinates</h2><p className="panel-intro">Minecraft portals use an 8:1 horizontal coordinate ratio between the Overworld and Nether.</p><form onSubmit={(event) => { event.preventDefault(); setResult({ x: netherCoordinate(Number(x), direction), z: netherCoordinate(Number(z), direction) }); }}><div className="form-grid"><NumberField id="portal-x" label="X coordinate" value={x} onChange={setX} step={1} /><NumberField id="portal-z" label="Z coordinate" value={z} onChange={setZ} step={1} /><div className="field"><label htmlFor="portal-direction">Convert</label><select id="portal-direction" value={direction} onChange={(event) => setDirection(event.target.value as typeof direction)}><option value="to-nether">Overworld → Nether</option><option value="to-overworld">Nether → Overworld</option></select></div></div><button className="primary-button" type="submit">Convert coordinates</button></form>{result !== null && <Result label="Target coordinates" value={`X ${result.x} · Z ${result.z}`} note="Y coordinates do not need conversion." />}</div>;
}

export function CoordinateConverter() {
  const [x, setX] = useState("0"); const [z, setZ] = useState("0"); const [direction, setDirection] = useState<"to-nether" | "to-overworld">("to-nether"); const [result, setResult] = useState<{ x: number; z: number } | null>(null);
  return <div className="panel calculator-panel"><h2>Convert dimensions</h2><p className="panel-intro">Convert X and Z coordinates using Minecraft&apos;s 8:1 Overworld-to-Nether ratio.</p><form onSubmit={(event) => { event.preventDefault(); setResult({ x: netherCoordinate(Number(x), direction), z: netherCoordinate(Number(z), direction) }); }}><div className="form-grid"><NumberField id="convert-x" label="X coordinate" value={x} onChange={setX} step={1} /><NumberField id="convert-z" label="Z coordinate" value={z} onChange={setZ} step={1} /><div className="field"><label htmlFor="convert-direction">Convert</label><select id="convert-direction" value={direction} onChange={(event) => setDirection(event.target.value as typeof direction)}><option value="to-nether">Overworld → Nether</option><option value="to-overworld">Nether → Overworld</option></select></div></div><button className="primary-button" type="submit">Convert coordinates</button></form>{result !== null && <Result label="Converted coordinates" value={`X ${result.x} · Z ${result.z}`} note="Only horizontal coordinates are converted." />}</div>;
}

export function StackCalculator() {
  const [count, setCount] = useState("128"); const [size, setSize] = useState("64"); const [result, setResult] = useState<ReturnType<typeof stackBreakdown> | null>(null);
  return <div className="panel calculator-panel"><h2>Break items into stacks</h2><p className="panel-intro">Enter an item count and the stack size for that item. Use 16 for items that stack to sixteen and 1 for non-stackable items.</p><form onSubmit={(event) => { event.preventDefault(); setResult(stackBreakdown(Number(count), Number(size))); }}><div className="form-grid"><NumberField id="item-count" label="Item count" value={count} onChange={setCount} min={1} /><NumberField id="stack-size" label="Stack size" value={size} onChange={setSize} min={1} /></div><button className="primary-button" type="submit">Calculate stacks</button></form>{result !== null && <Result label="Stack breakdown" value={`${result.stacks} full + ${result.remainder}`} note={`${result.slots} inventory slot${result.slots === 1 ? "" : "s"} needed.`} />}</div>;
}

export function DurabilityCalculator() {
  const [max, setMax] = useState("1561"); const [remaining, setRemaining] = useState("1000"); const [result, setResult] = useState<ReturnType<typeof durabilityDetails> | null>(null);
  return <div className="panel calculator-panel"><h2>Check item durability</h2><p className="panel-intro">Compare an item&apos;s remaining durability with its maximum durability. Enter values from the item tooltip or game UI.</p><form onSubmit={(event) => { event.preventDefault(); setResult(durabilityDetails(Number(max), Number(remaining))); }}><div className="form-grid"><NumberField id="max-durability" label="Maximum durability" value={max} onChange={setMax} min={1} /><NumberField id="remaining-durability" label="Remaining durability" value={remaining} onChange={setRemaining} min={0} /></div><button className="primary-button" type="submit">Calculate durability</button></form>{result !== null && <Result label="Durability remaining" value={`${result.remaining} / ${max}`} note={`${result.percentage.toFixed(1)}% remaining.`} />}</div>;
}

export function BeaconCalculator() {
  const [layers, setLayers] = useState("4"); const [result, setResult] = useState<number | null>(null);
  return <div className="panel calculator-panel"><h2>Count beacon pyramid blocks</h2><p className="panel-intro">Choose a pyramid size from one to four layers. The result counts the mineral blocks in the pyramid, excluding the beacon itself.</p><form onSubmit={(event) => { event.preventDefault(); setResult(beaconBlocks(Number(layers))); }}><div className="form-grid"><NumberField id="beacon-layers" label="Pyramid layers" value={layers} onChange={setLayers} min={1} /></div><button className="primary-button" type="submit">Calculate blocks</button></form>{result !== null && <Result label="Pyramid blocks" value={result.toLocaleString()} note={`A ${layers}-layer pyramid uses ${result.toLocaleString()} blocks.`} />}</div>;
}

export function SmeltingCalculator() {
  const [items, setItems] = useState("10"); const [seconds, setSeconds] = useState("10"); const [fuel, setFuel] = useState("80"); const [result, setResult] = useState<ReturnType<typeof smeltingDetails> | null>(null);
  return <div className="panel calculator-panel"><h2>Estimate smelting time</h2><p className="panel-intro">Enter the batch size, the recipe&apos;s smelting time, and how many seconds one fuel item burns.</p><form onSubmit={(event) => { event.preventDefault(); setResult(smeltingDetails(Number(items), Number(seconds), Number(fuel))); }}><div className="form-grid"><NumberField id="smelt-items" label="Items to smelt" value={items} onChange={setItems} min={1} /><NumberField id="smelt-time" label="Seconds per item" value={seconds} onChange={setSeconds} min={1} /><NumberField id="fuel-time" label="Fuel burn time (seconds)" value={fuel} onChange={setFuel} min={1} /></div><button className="primary-button" type="submit">Calculate smelting</button></form>{result !== null && <Result label="Estimated furnace time" value={`${Math.floor(result.totalSeconds / 60)}m ${result.totalSeconds % 60}s`} note={`At least ${result.fuelItems} fuel item${result.fuelItems === 1 ? "" : "s"} are needed for one furnace.`} />}</div>;
}

export function BrewingCalculator() {
  const [potions, setPotions] = useState("3"); const [result, setResult] = useState<ReturnType<typeof brewingDetails> | null>(null);
  return <div className="panel calculator-panel"><h2>Plan brewing batches</h2><p className="panel-intro">A brewing stand can process up to three bottles in one ingredient batch. Enter the number of finished potions you need.</p><form onSubmit={(event) => { event.preventDefault(); setResult(brewingDetails(Number(potions))); }}><div className="form-grid"><NumberField id="potion-count" label="Potions needed" value={potions} onChange={setPotions} min={1} /></div><button className="primary-button" type="submit">Calculate batches</button></form>{result !== null && <Result label="Brewing plan" value={`${result.batches} batch${result.batches === 1 ? "" : "es"}`} note={`Prepare ${result.bottles} water bottle${result.bottles === 1 ? "" : "s"}. Each batch uses one brewing ingredient.`} />}</div>;
}